export const MOCK_SERIES = [
    {
        id: '1',
        title: 'Solo Leveling',
        type: 'manhwa',
        status: 'completed',
        moods: ['hype'],
        genres: ['action', 'fantasy'],
        description: 'The weakest hunter becomes the world’s strongest predator.',
        reason: 'Perfect if you want pure power fantasy and incredible art.',
    },
    {
        id: '2',
        title: 'Berserk',
        type: 'manga',
        status: 'ongoing',
        moods: ['dark', 'emotional'],
        genres: ['fantasy', 'horror', 'seinen'],
        description: 'A wandering mercenary fights against destiny and demons.',
        reason: 'The pinnacle of dark fantasy and character depth.',
    },
    {
        id: '3',
        title: 'Spy x Family',
        type: 'anime',
        status: 'ongoing',
        moods: ['chill', 'hype'],
        genres: ['comedy', 'slice of life', 'action'],
        description: 'A spy, an assassin, and a telepath form a fake family.',
        reason: 'Wholesome, funny, and occasionally action-packed.',
    },
    {
        id: '4',
        title: 'Violet Evergarden',
        type: 'anime',
        status: 'completed',
        moods: ['emotional', 'chill'],
        genres: ['drama', 'slice of life'],
        description: 'A former soldier learns what "I love you" means.',
        reason: 'Visually stunning and guaranteed to make you cry.',
    },
    {
        id: '5',
        title: 'Chainsaw Man',
        type: 'manga',
        status: 'ongoing',
        moods: ['hype', 'dark'],
        genres: ['action', 'horror', 'shonen'],
        description: 'A boy merges with a chainsaw demon to hunt other devils.',
        reason: 'Chaotic, unpredictable, and surprisingly deep.',
    },
    {
        id: '6',
        title: 'Yotsuba&!',
        type: 'manga',
        status: 'ongoing',
        moods: ['chill'],
        genres: ['slice of life', 'comedy'],
        description: 'The everyday adventures of a strange little girl.',
        reason: 'The ultimate cure for a bad day.',
    },
    {
        id: '7',
        title: 'Attack on Titan',
        type: 'anime',
        status: 'completed',
        moods: ['hype', 'dark', 'emotional'],
        genres: ['action', 'mystery'],
        description: 'Humanity lives inside walls to hide from man-eating titans.',
        reason: 'A masterclass in plot twists and world-building.',
    },
    {
        id: '8',
        title: 'Monster',
        type: 'anime',
        status: 'completed',
        moods: ['dark', 'emotional'],
        genres: ['thriller', 'psychological'],
        description: 'A doctor saves a boy who grows up to be a true monster.',
        reason: 'A slow-burn psychological thriller that will haunt you.',
    },
    {
        id: '9',
        title: 'Horimiya',
        type: 'anime',
        status: 'completed',
        moods: ['chill', 'emotional'],
        genres: ['romance', 'slice of life'],
        description: 'Two popular students hide their true selves from everyone but each other.',
        reason: 'Realistic romance with lovable characters.',
    },
    {
        id: '10',
        title: 'One Piece',
        type: 'manga',
        status: 'ongoing',
        moods: ['hype', 'emotional'],
        genres: ['adventure', 'action', 'shonen'],
        description: 'A pirate adventure seeking the ultimate treasure.',
        reason: 'The greatest adventure epic ever told.',
    },
];

export const MOODS = [
    { id: 'hype', label: 'Hype', emoji: '🔥' },
    { id: 'dark', label: 'Dark', emoji: '🌑' },
    { id: 'chill', label: 'Chill', emoji: '🍃' },
    { id: 'emotional', label: 'Emotional', emoji: '💧' },
];

export const GENRES = [
    'action', 'adventure', 'comedy', 'drama', 'fantasy', 'horror', 'mystery', 'psychological', 'romance', 'slice of life', 'thriller'
];
